'use client'

import type { ComponentType } from 'react'
import {
  IconAccessible,
  IconAlertTriangle,
  IconAmbulance,
  IconAnchor,
  IconArmchair,
  IconArrowsHorizontal,
  IconBabyCarriage,
  IconBarbell,
  IconBath,
  IconBeach,
  IconBed,
  IconBike,
  IconBlind,
  IconBraille,
  IconBrain,
  IconBuilding,
  IconBuildingCommunity,
  IconBuildingCottage,
  IconBuildingMonument,
  IconBuildingSkyscraper,
  IconBuildingStore,
  IconBulb,
  IconBus,
  IconCalendarCheck,
  IconCalendarEvent,
  IconCalendarTime,
  IconCamera,
  IconCane,
  IconCar,
  IconCash,
  IconChefHat,
  IconCircleCheck,
  IconClock,
  IconCoffee,
  IconCompass,
  IconConfetti,
  IconCube,
  IconCurrencyReal,
  IconDirections,
  IconDisabled,
  IconDisabled2,
  IconDog,
  IconDoor,
  IconDoorEnter,
  IconDots,
  IconEar,
  IconEarOff,
  IconElevator,
  IconEye,
  IconEyeOff,
  IconFirstAidKit,
  IconFlag,
  IconFriends,
  IconGift,
  IconGlassFull,
  IconGripHorizontal,
  IconHandFinger,
  IconHandMove,
  IconHandStop,
  IconHeadphones,
  IconHeartHandshake,
  IconHomeHeart,
  IconId,
  IconInfoCircle,
  IconLamp,
  IconLanguage,
  IconLeaf,
  IconLetterCase,
  IconLifebuoy,
  IconMap2,
  IconMapPin,
  IconMapRoute,
  IconMessageLanguage,
  IconMessages,
  IconMoodKid,
  IconMoodSmile,
  IconMountain,
  IconMusic,
  IconOld,
  IconPalette,
  IconParking,
  IconPhone,
  IconPhoto,
  IconPlane,
  IconPlant,
  IconPlayerPlay,
  IconPool,
  IconPuzzle,
  IconRoad,
  IconRotate360,
  IconRoute,
  IconSailboat,
  IconScubaMask,
  IconShieldCheck,
  IconShip,
  IconSoup,
  IconSparkles,
  IconSpeakerphone,
  IconStairs,
  IconStairsDown,
  IconStar,
  IconStethoscope,
  IconSun,
  IconSunset,
  IconSwimming,
  IconTag,
  IconTags,
  IconTent,
  IconTextSize,
  IconTicket,
  IconToiletPaper,
  IconTool,
  IconTools,
  IconToolsKitchen2,
  IconToolsKitchen3,
  IconTree,
  IconTrees,
  IconTrekking,
  IconTrendingUp,
  IconUserCheck,
  IconUsers,
  IconVideo,
  IconView360,
  IconVolume,
  IconVolumeOff,
  IconWalk,
  IconWheelchair,
  IconWifi,
  IconWorld,
  IconCircle,
} from '@tabler/icons-react'

type TablerIcon = ComponentType<{ size?: number | string; stroke?: number | string; color?: string; 'aria-hidden'?: boolean }>

// Catálogo curado de ícones (biblioteca Tabler). A Área 04 grava no banco a
// chave em kebab-case (ex.: 'wheelchair'); só as chaves desta lista podem ser
// escolhidas, o que mantém o bundle pequeno.
export const ICONES: Record<string, TablerIcon> = {
  'wheelchair': IconWheelchair,
  'accessible': IconAccessible,
  'disabled': IconDisabled,
  'disabled-2': IconDisabled2,
  'old': IconOld,
  'cane': IconCane,
  'stairs': IconStairs,
  'stairs-down': IconStairsDown,
  'door-enter': IconDoorEnter,
  'door': IconDoor,
  'trending-up': IconTrendingUp,
  'arrows-horizontal': IconArrowsHorizontal,
  'grip-horizontal': IconGripHorizontal,
  'elevator': IconElevator,
  'toilet-paper': IconToiletPaper,
  'bath': IconBath,
  'parking': IconParking,
  'bus': IconBus,
  'car': IconCar,
  'road': IconRoad,
  'route': IconRoute,
  'map-route': IconMapRoute,
  'map-2': IconMap2,
  'map-pin': IconMapPin,
  'directions': IconDirections,
  'compass': IconCompass,
  'hand-finger': IconHandFinger,
  'hand-stop': IconHandStop,
  'hand-move': IconHandMove,
  'message-language': IconMessageLanguage,
  'messages': IconMessages,
  'language': IconLanguage,
  'letter-case': IconLetterCase,
  'text-size': IconTextSize,
  'speakerphone': IconSpeakerphone,
  'eye': IconEye,
  'eye-off': IconEyeOff,
  'braille': IconBraille,
  'blind': IconBlind,
  'headphones': IconHeadphones,
  'volume': IconVolume,
  'volume-off': IconVolumeOff,
  'ear': IconEar,
  'ear-off': IconEarOff,
  'video': IconVideo,
  'player-play': IconPlayerPlay,
  'camera': IconCamera,
  'photo': IconPhoto,
  'view-360': IconView360,
  'rotate-360': IconRotate360,
  'cube': IconCube,
  'brain': IconBrain,
  'puzzle': IconPuzzle,
  'armchair': IconArmchair,
  'bulb': IconBulb,
  'lamp': IconLamp,
  'mood-smile': IconMoodSmile,
  'dog': IconDog,
  'heart-handshake': IconHeartHandshake,
  'user-check': IconUserCheck,
  'users': IconUsers,
  'friends': IconFriends,
  'mood-kid': IconMoodKid,
  'baby-carriage': IconBabyCarriage,
  'swimming': IconSwimming,
  'scuba-mask': IconScubaMask,
  'pool': IconPool,
  'beach': IconBeach,
  'sun': IconSun,
  'sunset': IconSunset,
  'trees': IconTrees,
  'tree': IconTree,
  'leaf': IconLeaf,
  'plant': IconPlant,
  'mountain': IconMountain,
  'trekking': IconTrekking,
  'walk': IconWalk,
  'bike': IconBike,
  'tent': IconTent,
  'anchor': IconAnchor,
  'sailboat': IconSailboat,
  'ship': IconShip,
  'tools-kitchen-2': IconToolsKitchen2,
  'tools-kitchen-3': IconToolsKitchen3,
  'chef-hat': IconChefHat,
  'coffee': IconCoffee,
  'glass-full': IconGlassFull,
  'soup': IconSoup,
  'building': IconBuilding,
  'building-skyscraper': IconBuildingSkyscraper,
  'building-cottage': IconBuildingCottage,
  'building-community': IconBuildingCommunity,
  'building-monument': IconBuildingMonument,
  'building-store': IconBuildingStore,
  'home-heart': IconHomeHeart,
  'bed': IconBed,
  'plane': IconPlane,
  'ticket': IconTicket,
  'confetti': IconConfetti,
  'music': IconMusic,
  'palette': IconPalette,
  'barbell': IconBarbell,
  'stethoscope': IconStethoscope,
  'first-aid-kit': IconFirstAidKit,
  'ambulance': IconAmbulance,
  'shield-check': IconShieldCheck,
  'lifebuoy': IconLifebuoy,
  'calendar-check': IconCalendarCheck,
  'calendar-event': IconCalendarEvent,
  'calendar-time': IconCalendarTime,
  'clock': IconClock,
  'id': IconId,
  'tool': IconTool,
  'tools': IconTools,
  'wifi': IconWifi,
  'phone': IconPhone,
  'world': IconWorld,
  'tag': IconTag,
  'tags': IconTags,
  'cash': IconCash,
  'currency-real': IconCurrencyReal,
  'gift': IconGift,
  'star': IconStar,
  'sparkles': IconSparkles,
  'info-circle': IconInfoCircle,
  'alert-triangle': IconAlertTriangle,
  'flag': IconFlag,
  'circle-check': IconCircleCheck,
  'dots': IconDots,
}

export const CHAVES_ICONES = Object.keys(ICONES)

export default function Icone({
  nome,
  size = 20,
  stroke = 1.75,
  color,
}: {
  nome: string | null | undefined
  size?: number
  stroke?: number
  color?: string
}) {
  const Componente = (nome && ICONES[nome]) || IconCircle
  return <Componente size={size} stroke={stroke} color={color} aria-hidden />
}
